server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:mysql://catalog-db:3306/catalog_db?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:catalog_user}
    password: ${DB_PASSWORD:catalog_pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
#        namespace: dev
#        group: COURSEHUB_GROUP
        ephemeral: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        username: nacos # 默认用户名
        password: nacos # 默认密码
        access-token: VGhpc0lzTXlTdXBlckxvbmdBbmRBYnNvbHV0ZWx5U2VjdXJlU2VjcmV0S2V5Rm9yTmFjb3NBdXRoMTIzNDU=

logging:
  level:
    com.zjgsu.pjt.catalog: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
