server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=UTC
    username: user_user
    password: user_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
#        namespace: dev
#        group: COURSEHUB_GROUP
        ephemeral: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000

# 暴露所有 Actuator 端点，特别是 /health，以便 Nacos 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.zjgsu.pjt.user: INFO
    org.springframework.web: INFO
